### ISSUE TITLE
Allow checking for alternative emails in get-slack-handle.py

### ISSUE THREAD

**Issue by acesdm** [strongdm/accessbot#184]
**Is your feature request related to a problem? Please describe.**
Right now, our own supportbot is using alternative emails but get_slack_handle.py only checks the primary email address.

**Describe the solution you'd like**
Allow for checking alternative emails if configured 

**Describe alternatives you've considered**
ask the user to find their own correct username

**Additional context**

**IMPORTANT**: Remember to select a label and project

**Comment by vassalo** [comment]
Unfortonately, this is not going to be implemented because it is impractical.
Here's why: in the script we'd need to iterate through all users of the organization to check the "profile custom fields" of each one. But, the "WebClient.users_list" method does not return the custom fields from the users profiles, so we'd need to make a request for each user to get their entire profile and that seems like an overkill.

**Comment by vassalo** [comment]
Unfortonately, this is not going to be implemented because it is impractical.
Here's why: in the script we'd need to iterate through all users of the organization to check the "profile custom fields" of each one. But, the "WebClient.users_list" method does not return the custom fields from the users profiles, so we'd need to make a request for each user to get their entire profile and that would be tricky due to the slack api rate limit.
