### ISSUE TITLE
Slack/accessbot does not return anything when an unknown command is sent

### ISSUE THREAD

**Issue by jfb3524** [strongdm/accessbot#240]
users think it's not working when nothing is returned from accessbot

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**IMPORTANT**: Remember to select a label and project

**Comment by camposer** [comment]
Returning a message for every entered "text" could be too much, but we could definitely add a message (on thread) to the original access request message when it's valid. That way, the user would have a confirmation from the bot when the request is valid - Only for Manual Approvals, since the feedback for the Automatic Approvals is immediate.

**Comment by camposer** [comment]
Hi @jfb3524 

After checking AccessBot we can confirm that it's returning a message indicating that the request was valid

![image](https://user-images.githubusercontent.com/313803/166929009-333c976a-0c3d-456d-b408-9dbfcc935777.png)

Maybe the problem is more about expectations from the users. Do you think that just saying that a request was received and it's valid solves the problem, or do you still would like to "error" any non-command message received by the bot?

If you "error" any non-command message your slack channel can get very messy - always saying that's not a valid command.
