### ISSUE TITLE
Show available resources based on membership of requesting user

### ISSUE THREAD

**Issue by mdube667** [strongdm/accessbot#258]
**Is your feature request related to a problem? Please describe.**
No, the customer would like a new feature.

**Describe the solution you'd like**
They'd like to be able to show resources that are tagged with the roles that the user calling "show available resources" has.

In their own words:

- We have
Roles:
+ DevOps 
    - Tags: 
             team=devops
             env=stagging,production
+ Database Admin 
    - Tags: 
             team=database,devops
             env=stagging,production
+ Developer Project A 
   - Tags: 
             team=project-a,devops
             env=staging
Resources:
+ Redis Database 
    - Tags:
            team=database,devops
            env=production
+ Staging Server 
    - Tags:
           team=project-a,devops
           env=staging

With Slackbot - when you're a member of team Database - you execute the command: 
    show available resources
=> We want you to be able to view resources with the tag: team=database. We expect result:
Resources:
    Redis Database - (Match the Tag: team=database, env=production)

And when you're member of team Dev Project A - Resource will be showed:
Resources:
   Staging Server - (Match the Tag: team=project-a, env=staging)

And with you're member of DevOps team:
Resources:
   Redis Database
   Staging Server

**Describe alternatives you've considered**
We tried the currently available tagging of resources. that's what they're using now but they'd like the full feature.

**Comment by camposer** [comment]
@mdube667 please validate with the customer the use case for this. Because if a user already has a role he should already has access to the resource.

**Comment by tonylokko** [comment]
@camposer I had a follow up meeting with the customer around this. Basically they want to make it so an admin can tag resources + roles so that only the roles+resources tagged display as available for that user to request at all.

Ie if i have a dba tag on my user, only and say 'show available roles' only roles and resources that are already tagged with dba will show up. 

They want to do just in time access for everything, so the users by default will request access to what they need as they need it. more of a zero privilage approach i guess. They want to make it so an end user has no visibillity of resources outside of what the admin allows them to see in slackbot.

**Comment by camposer** [comment]
We can resolve this using an allowlist approach. It would end up being something like:

**AccessBot config**
```
SDM_GROUPS_TAG=sdm-groups
SDM_ALLOW_GROUP_TAG=allow-resource
```

**SDM config**

User: 
- Name: Daniel
- Tags: sdm-groups=dev

Resource:
- Name: PostgreSQL
- Tags: allow-resource=dev,ops

Role:
- Name: My Role
- Tags: allow-resource=ops

----

Daniel can request access to `PostgreSQL` but not to `My Role`

**Comment by camposer** [comment]
@tonylokko please validate with the customer if the proposed solution would work for them...

**Comment by tonylokko** [comment]
explained the proposed solution to check if it will work for the end user, based on what is described above it sounds like it will do what is needed. Drew a quick diagram to explain, i think we're good to implement.
