### ISSUE TITLE
Allow for different administrators to operate with different users

### ISSUE THREAD

**Issue by wrenhunter** [strongdm/accessbot#7]
**Is your feature request related to a problem? Please describe.**
Larger, production scenarios involve different hierarchies. One might want to have admin1 approve requests for all support users, but admin2 for all Engineering users.

**Describe the solution you'd like**
I don't have a clear idea of how this would be implemented. Perhaps a dictionary that maps users to admins. Upon request, use the requestor's email to find the correct admin?

**Comment by vassalo** [comment]
Hey, @wrenhunter!
After a lot of thinking and trying to implement this feature, we came to the conclusion that this flow is very costly, because we would have to make a lot of requests to get the individual "approvers" info to be able to send a DM for each one of them.

So we came up with a similar approach and would like to know what you think about it. Our suggestion is: a regular user would have an "approver-group" tag that stores the name of a Slack Channel correspondent to their encharged "approvers", similar to what we have for resources. Then, every access request made from a user with an "approver-group" tag would go to the provided channel and only the users inside it would be able to approve/deny their requests.

Sounds good?

**Comment by wrenhunter** [comment]
Hi @vassalo thanks for the update. Let me post a hypothetical scenario to make sure I understand your proposal.

Let's say that I'm on the Support team, and my requests need to be approved by "Arthur". You are on the Engineering team, and your requests must be approved by "Rhonda".  My proposal was that Accessbot would query my user and (somehow) find Arthur's name and send a DM.

Your proposal is that my user has a tag `support-team`. That tag is mapped in the Accessbot config to a channel called `support_managers`. Arthur is a member of that channel, so he approves for me. Likewise, you make a request, and the message goes to channel `eng_managers`, where "Rhonda" is a member.

Do I understand that correctly? If so, I "approve" 😄

**Comment by vassalo** [comment]
Almost there, @wrenhunter. hahaha
Let me "fix" your scenario and then you can give another feedback.

Your user would have a tag called `approvers-channel` (configurable via `plugin config`) and its value would be "support_managers". And my user would have the same `approvers-channel` tag but with the value "eng_managers". That way, your requests would go to the **#support_managers** channel and Arthur would approve them from there.

This is similar to what we have for resources, if a resource has an `approvers-channel` tag, we get the value (channel name) from it and send the requests to that channel.

**Comment by wrenhunter** [comment]
Thanks for the update, sounds like a good plan!

**Comment by camposer** [comment]
Resources config should have higher priority than users config
