### ISSUE TITLE
K8s Authenticating Proxy resources in org break the `show available resources` command

### ISSUE THREAD

**Issue by wrenhunter** [strongdm/accessbot#71]
**Describe the bug**
Running `show available resources` in an org with k8s beta resources gives this error:

List resources failed: ("unknown resource type 'kubernetesauthenticatingproxy'", 2)

I think we've seen this recently with other beta resources, and it's related to not having/running our latest Python SDK.

**To Reproduce**
I used the latest image from [here](https://github.com/strongdm/accessbot/releases/tag/1.0.0).
In your test org, add a k8s beta resource. 
Run `show available resources` in Slack.

**Expected behavior**
You see resources.

**Comment by camposer** [comment]
There's a bug in the SDK, reported internally #3702 

I'll keep an eye on the resolution, and then update here.

**Comment by camposer** [comment]
I'll update the title to only refer to Authenticating Proxy resources.

**Comment by camposer** [comment]
Because K8s Authenticating Proxy isn't approved yet, the team is planning to remove `kubernetesauthenticatingproxy` from the SDK. In that case, that type of resources will be returned as None, and we already have a condition for handling those.

Is a user has this type of resources, for now he/she just would need to remove them in order to use `show available resources`.
